IMAGE_NAME = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
      
    # haproxy configuration
    config.vm.define "haproxy" do |haproxy|
        haproxy.vm.box = IMAGE_NAME
        haproxy.vm.network "private_network", ip: "192.168.50.13"
        haproxy.vm.hostname = "haproxy"

        # Virtualbox configuration
        haproxy.vm.provider "virtualbox" do |v|
                 v.memory = 2048
		 v.cpus = 1
        end
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.config_file = "ansible.cfg"
        ansible.playbook = "playbook.yml"
        ansible.groups = {
            haproxy: ["haproxy"]
        }
    end

end
