IMAGE_NAME = "ubuntu/bionic64"
N = 2

Vagrant.configure("2") do |config|

    # Virtualbox configuration
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 1
    end
      
    # K8s master configuration
    config.vm.define "master-kube" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "master-kube"

        # Virtualbox configuration
        master.vm.provider "virtualbox" do |v|
            v.cpus = 2
        end
    end

    # K8s worker configuration
    (1..N).each do |i|
        config.vm.define "node-#{i}-kube" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}-kube"
        end
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.config_file = "ansible.cfg"
        ansible.playbook = "playbook.yml"
        ansible.groups = {
            masters: ["master-kube"],
            nodes: ["node-1-kube","node-2-kube"]
        }
    end

end
